name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: week3-containers-api/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t shortener-api week3-containers-api/api

  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - week1-static-site/terraform
          - week2-vpc-lab/terraform
          - week3-containers-api/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
        working-directory: ${{ matrix.dir }}
      - run: terraform init -backend=false
        working-directory: ${{ matrix.dir }}
      - run: terraform validate
        working-directory: ${{ matrix.dir }}
